# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Insert(object):
    def setupUi(self, Insert):
        Insert.setObjectName("Insert")
        Insert.resize(420, 260)
        self.gridlayout = QtWidgets.QGridLayout(Insert)
        self.gridlayout.setObjectName("gridlayout")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(Insert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.lineName = QtWidgets.QLineEdit(Insert)
        self.lineName.setMouseTracking(False)
        self.lineName.setInputMask("")
        self.lineName.setMaxLength(10)
        self.lineName.setFrame(True)
        self.lineName.setObjectName("lineName")
        self.vboxlayout.addWidget(self.lineName)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Insert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.comboType = QtWidgets.QComboBox(Insert)
        self.comboType.setMaxVisibleItems(3)
        self.comboType.setObjectName("comboType")
        self.vboxlayout.addWidget(self.comboType)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(Insert)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.vboxlayout.addWidget(self.label_3)
        self.comboPos = QtWidgets.QComboBox(Insert)
        self.comboPos.setObjectName("comboPos")
        self.vboxlayout.addWidget(self.comboPos)
        self.gridlayout.addLayout(self.vboxlayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Insert)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridlayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem2, 1, 0, 1, 1)

        self.retranslateUi(Insert)
        self.comboType.setCurrentIndex(-1)
        self.buttonBox.accepted.connect(Insert.accept)
        self.buttonBox.rejected.connect(Insert.reject)
        QtCore.QMetaObject.connectSlotsByName(Insert)
        Insert.setTabOrder(self.lineName, self.comboType)
        Insert.setTabOrder(self.comboType, self.comboPos)
        Insert.setTabOrder(self.comboPos, self.buttonBox)

    def retranslateUi(self, Insert):
        _translate = QtCore.QCoreApplication.translate
        Insert.setWindowTitle(_translate("Insert", "Insert field"))
        self.label.setText(_translate("Insert", "Field name:"))
        self.label_2.setText(_translate("Insert", "Field type:"))
        self.label_3.setText(_translate("Insert", "Insert at position:"))

